config/routes.rb
Rails.application.routes.draw do
  root to: 'list#new'
  post 'list/new'
  get 'list/new'
  get 'list/data'
  resources :students
  resources :courses
  resources :institutions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, :grade, :institution, presence: true

  belongs_to :institution
  has_many :students
end

app/models/institution.rb
class Institution < ApplicationRecord
  validates :name, :grade, presence: true

  has_many :courses
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, :grade, :course, presence: true

  belongs_to :course

  def institution
    course.institution
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy]

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit; end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to root_path, notice: 'Curso criado.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to root_path, notice: 'Curso atualizado.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Curso apagado.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def course_params
    params.require(:course).permit(:name, :grade, :institution_id)
  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: %i[show edit update destroy]

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit; end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to root_path, notice: 'Instituição criada.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to root_path, notice: 'Instituição atualizada.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Instituição apagada.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_institution
    @institution = Institution.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def institution_params
    params.require(:institution).permit(:name, :grade)
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  def new
    @list = ListService.new(list_params).data
  end

  def list_params
    params.permit(:institution_name, :institution_grade, :course_name, :course_grade, :student_grade)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[show edit update destroy]

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit; end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to root_path, notice: 'Estudante criado.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to root_path, notice: 'Estudante atualizado.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Estudante apagado.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def student_params
    params.require(:student).permit(:name, :grade, :course_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-error'
    when 'alert'
      'alert-block'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/views/courses/_form.html.erb
<div class="container" style="margin-top:30px">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><b>Novo Curso</b></h4>
      </div>
      <div class="panel-body">
        <%= form_with(model: course, local: true) do |form| %>
          <% if course.errors.any? %>
            <div id="error_explanation" class="alert alert-danger">
            <ul>
              <% course.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div style="margin-bottom: 12px" class="input-group">
            <%= form.text_field :name, class: 'form-control', placeholder: Course.human_attribute_name(:name) %>
          </div>
          <div style="margin-bottom: 12px" class="input-group">
            <%= form.text_field :grade, class: 'form-control', placeholder: Course.human_attribute_name(:grade) %>
          </div>

          <div style="margin-bottom: 12px" class="input-group">
            <%= collection_select(:course, :institution_id, Institution.all, :id, :name, prompt: 'Selecione a Instituição', class: 'form-control') %>
          </div>

          <div class="actions" class="form-group text-center">
            <%= form.submit 'Salvar', class: 'btn btn-success' %>
            <%= link_to 'Voltar', root_path, class: "btn btn-default"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

app/views/courses/new.html.erb
<%= render 'form', course: @course %>

app/views/institutions/_form.html.erb
<div class="container" style="margin-top:30px">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><b>Nova Instituição</b></h4>
      </div>
      <div class="panel-body">
      <%= form_with(model: institution, local: true) do |form| %>
        <% if institution.errors.any? %>
          <div id="error_explanation"  class="alert alert-danger">
            <ul>
            <% institution.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div style="margin-bottom: 12px" class="input-group">
          <%= form.text_field :name, class: 'form-control', placeholder: Institution.human_attribute_name(:name) %>
        </div>
        <div style="margin-bottom: 12px" class="input-group">
          <%= form.text_field :grade, class: 'form-control', placeholder: Institution.human_attribute_name(:grade) %>
        </div>
        <div class="actions" class="form-group text-center">
          <%= form.submit 'Salvar', class: 'btn btn-success' %>
          <%= link_to 'Voltar', root_path, class: "btn btn-default"%>
        </div>
      <% end %>

app/views/institutions/edit.html.erb
<%= render 'form', institution: @institution %>

app/views/institutions/new.html.erb
<%= render 'form', institution: @institution %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Approva</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top navbar-inverse">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Cadastrar Instituição', new_institution_path %></li>
          <li><%= link_to 'Cadastrar Curso', new_course_path %></li>
          <li><%= link_to 'Cadastrar Estudante', new_student_path %></li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/list/new.html.erb
<div class="container-fluid" style="margin-top:30px">
  <div class="col-md-12">
  <% flash.each do |key, value| %>
      <div class="alert <%= bootstrap_class_for(key) %>"><%= value %></div>
    <% end %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><b>Lista Geral</b></h4>
      </div>
      <div class="panel-body">
        <%= form_tag list_new_path do %>
          <div class='col-md-12'>
            <div class='col-sm-2'>
              <%= text_field_tag 'institution_name', nil, placeholder: 'INSTITUIÇÃO',  class: 'form-control' %>
            </div>
            <div class='col-sm-2'>
              <%= text_field_tag 'institution_grade', nil, placeholder: 'MÉDIA GERAL',  class: 'form-control col-sm-2' %>
            </div>
            <div class='col-sm-2'>
              <%= text_field_tag 'course_name', nil, placeholder: 'CURSO',  class: 'form-control col-sm-2' %>
            </div>
            <div class='col-sm-2'>
              <%= text_field_tag 'course_grade', nil, placeholder: 'MÉDIA CURSO',  class: 'form-control col-sm-2' %>
            </div>
            <div class='col-sm-2'>
              <%= text_field_tag 'student_grade', nil, placeholder: 'MÉDIA ALUNO',  class: 'form-control col-sm-2'%>
            </div>
            <%= button_tag 'Filtrar', class: 'btn btn-success col-sm-2' %>
          </div>
        <% end %>
        <hr><hr>
        <table class='table table-bordered'>
            <% @list.each do |item| %>
              <% if @old_institution_id != item.institution_id %>
                <thead>
                  <tr>
                    <th><%= Institution.human_attribute_name :name %></th><td><%= item.institution_name %></td>
                    <th><%= Institution.human_attribute_name :grade %></th><td><%= item.institution_grade %></td>
                    <th colspan="3"></th>
                    <th> <%= link_to 'Editar', edit_institution_path(id: item.institution_id) %></th>
                  </tr>
                </thead>
              <% end %>

              <% if !item.course_id.nil? && @old_course_id != item.course_id %>
                <thead>
                  <tr style="background-color:#d1e0e0;">
                    <th></th>
                    <th><%= Course.human_attribute_name :name %></th><td><%= item.course_name %></td>
                    <th><%= Course.human_attribute_name :grade %></th><td><%= item.course_grade %></td>
                    <th colspan="2"></th>
                    <th> <%= link_to 'Editar', edit_course_path(id: item.course_id) %></th>
                  </tr>
                </thead>

              <% end %>

              <% if !item.student_id.nil? && @old_student_id != item.student_id %>
                <thead>
                  <tr style="background-color:#b3cccc;">
                    <th></th><th></th>
                    <th><%= Student.human_attribute_name :name %></th><td><%= item.student_name %></td>
                    <th><%= Student.human_attribute_name :grade %></th><td><%= item.student_grade %></td>
                    <th></th>
                    <th> <%= link_to 'Editar', edit_student_path(id: item.student_id) unless item.student_id.blank? %></th>
                  </tr>
                </thead>

              <% end %>
              <% @old_institution_id = item.institution_id %>
              <% @old_course_id = item.course_id %>
              <% @old_student_id = item.student_id %>

            <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/students/_form.html.erb
<div class="container" style="margin-top:30px">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><b>Novo Aluno</b></h4>
      </div>
      <div class="panel-body">
      <%= form_with(model: student, local: true) do |form| %>
        <% if student.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <ul>
            <% student.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div style="margin-bottom: 12px" class="input-group">
          <%= form.text_field :name, class: 'form-control', placeholder: Student.human_attribute_name(:name) %>
        </div>

        <div style="margin-bottom: 12px" class="input-group">
          <%= form.text_field :grade, class: 'form-control', placeholder: Student.human_attribute_name(:grade) %>
        </div>

        <div style="margin-bottom: 12px" class="input-group">
          <%= collection_select(:student, :course_id, Course.all, :id, :name, prompt: 'Selecione o Curso', class: 'form-control') %>
        </div>

        <div class="actions" class="form-group text-center">
          <%= form.submit 'Salvar', class: 'btn btn-success' %>
          <%= link_to 'Voltar', root_path, class: "btn btn-default"%>
        </div>
      <% end %>

app/views/students/edit.html.erb
<%= render 'form', student: @student %>

app/views/students/new.html.erb
<%= render 'form', student: @student %>